/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import gestock.GeStock;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author HP
 */
public class home1 extends javax.swing.JFrame {
    
    /**
     * Creates new form home1
     */
    public home1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        rdFrancais = new javax.swing.JRadioButton();
        rdAnglais = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSelected = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rdFrancais);
        rdFrancais.setText("Francais");
        rdFrancais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdFrancaisMouseClicked(evt);
            }
        });
        rdFrancais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFrancaisActionPerformed(evt);
            }
        });
        getContentPane().add(rdFrancais, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        buttonGroup1.add(rdAnglais);
        rdAnglais.setText("Anglais");
        getContentPane().add(rdAnglais, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jLabel1.setText("Langue :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 85, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel2.setText("Choisissez la langue");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 200, 30));

        btnSelected.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnSelected.setText("Ok");
        btnSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectedActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelected, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdFrancaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFrancaisActionPerformed
        
    }//GEN-LAST:event_rdFrancaisActionPerformed

    private void rdFrancaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdFrancaisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rdFrancaisMouseClicked

    private void btnSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectedActionPerformed
        //Recuperation de la langue selectionnee
        
        try{
            String langueC = getSelectedLanguage();
        
        //Fermeture de l'interface de selection
        home1.this.setVisible(false);
        
        //Ouverture de l'interface de login avec la langue selectionnee
        Login log = new Login(langueC);
        log.setVisible(true);
        dispose();
        }catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSelectedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelected;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rdAnglais;
    private javax.swing.JRadioButton rdFrancais;
    // End of variables declaration//GEN-END:variables

    public String getSelectedLanguage() {
        String langue;
        if(rdFrancais.isSelected()) {
            langue = "fr";
        }else if (rdAnglais.isSelected()) {
            langue = "en";
        }else {
            langue = "fr";
        }
        return langue;
    }
}
